export const WS_CONSTANTS = {
  THROTTLE: 2000,
  HEARTBEAT_INTERVAL: 30_000,
  RECONNECT_MAX_ATTEMPTS: 5,
  DISPLAY_TIMEOUT_MS: 5000,
} as const;

export const MOCK_CURRENT_USER_ID = 'user1';

export const CONVERSATION_CACHE = {
  TTL_MS: 30_000,
} as const;